services:
  - type: web
    name: ai-commit-server
    env: docker
    plan: free
    rootDir: server
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BACKEND
        value: gemini
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
